#!/usr/bin/env python3

FILE_PATH = "../theProblem/"
FILE_NAME = "a_example.txt"


def loadImagesFromFile(filePath):
    with open(filePath, "r") as file:
        r = file.read().split("\n")
    imgs = [line.split() for line in r[1:]]
    return imgs


if __name__ == "__main__":
    imgs = loadImagesFromFile(FILE_PATH + FILE_NAME)
